### ISSUE TITLE
Ruby Gem Version is behind github repo

### ISSUE THREAD

**Issue by JustinLloyd** [paul/progress_bar#35]
The version that is installed using "gem install progress_bar" is an older version than the code that exists in the github repo.

**Comment by paul** [comment]
Sorry, I somehow missed this bug report. I can't reproduce:

```
$ gem install progress_bar
Successfully installed progress_bar-1.0.5
1 gem installed
```

Can you provide some more info?

**Comment by h6y3** [comment]
I think perhaps the version number needed to be incremented.  For example, the module WithProgres doesn't seem to exist in the gem.  I didn't do a whole lot of due diligence on this but when I manually added the enumerable code in my class, I was able to take advantage of the module.  It would be great to update the gem rather than have to build the gem from source.

**Comment by paul** [comment]
Ah, I see what you're saying. I thought you meant the version here was newer than the version on rubygems.org, but both are 1.0.5. I'll release a 1.1.0 shortly.
