### ISSUE TITLE
How to show multiple different Progress bars?

### ISSUE THREAD

**Issue by fguillen** [paul/progress_bar#65]
I would like to monitor multiple simultaneus processes. I tried this

```
require 'progress_bar'

bar = ProgressBar.new
bar2 = ProgressBar.new

100.times do
  sleep 0.1
  bar.increment!
  bar2.increment!
end
```

But no, luck. Only one progress bar is shown

**Comment by paul** [comment]
Yeah, printing the 2nd bar would "wipe out" the first in the display. This isn't really a use-case I though of, but I can see the utility of it (like the docker cli download progress bars).

It'd be kinda tricky to implement, since every bar would have to know about every other bar, to know how many lines to clear from the terminal, and re-render all the bars.

I'd probably accept a PR, if you want to take a stab at it, though.

**Comment by paul** [comment]
Closing this for now.
